---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nova"
  title: "Nova Frontend"
  annotations:
    backstage.io/techdocs-ref: dir:./doc
    sonarqube.org/project-key: musement-nova
  links:
    - url: https://app.datadoghq.com/rum/performance-monitoring?query=%40application.id%3A0884692d-b516-4019-898f-58b23d9c95ba%20%40session.type%3Auser%20env%3Aprod&filters=%5B%22env%22%2C%22service%22%2C%22version%22%2C%22%40session.type%22%2C%22%40geo.country%22%2C%22%40device.type%22%5D&fromUser=false&tab=overview
      title: Logs | Prod
      icon: dashboard
    - url: https://app.datadoghq.com/rum/performance-monitoring?query=%40application.id%3A0884692d-b516-4019-898f-58b23d9c95ba%20%40session.type%3Auser%20env%3Apre&filters=%5B%22env%22%2C%22service%22%2C%22version%22%2C%22%40session.type%22%2C%22%40geo.country%22%2C%22%40device.type%22%5D&fromUser=false&tab=overview
      title: Logs | Pre
      icon: dashboard
    - url: https://app.datadoghq.com/rum/performance-monitoring?query=%40application.id%3A0884692d-b516-4019-898f-58b23d9c95ba%20%40session.type%3Auser%20env%3Atest&filters=%5B%22env%22%2C%22service%22%2C%22version%22%2C%22%40session.type%22%2C%22%40geo.country%22%2C%22%40device.type%22%5D&fromUser=false&tab=overview
      title: Logs | Test
      icon: dashboard
  tags:
    - javascript
    - typescript
    - html
    - css
    - vue
    - vite
    - "application:nova"
    - "businessunit:ancillarysourcing"
spec:
  type: service
  owner: "group:default/tui-musement-nova"
  lifecycle: production
  consumesApis:
    - contract-master-data-api
