export const mockDistributionData = {
  creation_date: "2024-06-20T05:03:11.079Z",
  updated_date: "2024-07-19T06:56:05.154Z",
  id: "182368a2-2879-4a43-b5f7-94fdc3e59641",
  reference_code: "EXP0016118",
  supplier_id: "082d65c7-3d18-484b-9dc5-6e33ef73be49",
  media_content: { id: "f1ea3518-47dd-4559-bc78-6a0147963bc8", distribution_status: "NOT_READY" },
  translation_content_list: [
    { id: "d6d6dd71-5914-407b-91d4-f1aaa743e7ee", language_code: "es", distribution_status: "READY" },
    { id: "80f4b554-2572-40de-8101-73b0cc3f03cd", language_code: "en", distribution_status: "NOT_READY" },
    { id: "0fcfe9cd-5b32-4e49-bc93-77e14a9a4c77", language_code: "it", distribution_status: "NOT_READY" },
    { id: "75d1e590-2c57-46bf-82e2-7d90c2313f12", language_code: "de", distribution_status: "NOT_READY" },
    { id: "3c688577-370c-4f6e-99e2-600ebf30377e", language_code: "fr", distribution_status: "NOT_READY" },
    { id: "b7ec8df9-aae3-4ecf-ae0e-5e923e352c45", language_code: "nl", distribution_status: "NOT_READY" },
    { id: "9e3492b6-a207-4166-b1c9-c4e541569e14", language_code: "pl", distribution_status: "NOT_READY" },
    { id: "5fe5b738-b873-42bc-b62e-b4824479fe59", language_code: "pt", distribution_status: "NOT_READY" },
    { id: "55521d3a-9c3a-48d6-a326-5e9f4cfae557", language_code: "ru", distribution_status: "NOT_READY" },
    { id: "e4302e37-cdef-444b-8ba4-e5f6c1090639", language_code: "dk", distribution_status: "NOT_READY" },
    { id: "20a1f7fa-964a-4637-bc0e-55dde4be87a1", language_code: "no", distribution_status: "NOT_READY" },
    { id: "dc3c208a-7dfa-45b2-8df3-a20a5954fcd6", language_code: "fi", distribution_status: "NOT_READY" },
    { id: "2a94e87d-290c-4dc9-b6c7-7e920df14c1e", language_code: "se", distribution_status: "NOT_READY" },
  ],
  global_status: "NOT_READY",
  curation_level: "DEDICATED",
  priority: 8,
  imported: false,
};

export const mockCurationRevision = {
  id: "5756d8e8-f836-4fed-a6f0-ab176b22a17e",
  creation_date: "2024-06-06T12:45:22.168",
  updated_date: "2024-06-07T08:49:42.562",
  experience_id: "6ab12cef-b5bf-4719-ba23-d89edc79af08",
  reference_code: "EXP0008991",
  supplier_id: "082d65c7-3d18-484b-9dc5-6e33ef73be49",
  version_id: "v3",
  version_status: "ARCHIVED",
  user_version: "tommaso.bartolucci",
  experience_commercial_information: {
    experience_media: {
      id: "76b24e64-f277-4ff1-8f95-c3636a970b84",
      flow_code: "MEDIA",
      status_code: "READY",
      images: [
        {
          file_name: "thumb_4582441_cover.jpg",
          preview_url: "https://tuigroup.fotoware.cloud/fotoweb/embed/2023/05/45dac52404b547ad8d416c917f53720c.jpg",
          visualization_order: 1,
          image_type: "GALLERY",
          creation_date: "2024-05-24T08:33:36.996",
          updated_date: "2024-05-24T08:33:36.996",
        },
      ],
    },
    translations: [
      {
        language_code: "pt",
        experience_translation: {
          id: "f29b537b-a4cb-468d-8172-2cc2c980887c",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.781",
          updated_date: "2024-05-24T08:34:46.667",
        },
        customs: {
          custom_highlights: [
            {
              id: "b3cf9d2b-cd40-4796-81b3-ab9ba4c232c7",
              name: "Any custom highlights",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
            },
          ],
          custom_included: [
            {
              id: "c51db647-dcc6-4c42-82b0-021aa760b2e6",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "5eaaef35-b289-4792-bbe0-b842fa184c2e",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "087a6315-dae2-45a1-90ca-064680f22229",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "fr",
        experience_translation: {
          id: "359dc9c2-3db8-4f6b-a32c-d85f0bbc0fab",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.767",
          updated_date: "2024-05-24T08:33:22.767",
        },
        customs: {
          custom_highlights: [
            {
              id: "0f396c55-fccc-4645-8f43-dc2eb8e603f9",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "2a582455-8d66-4435-bfca-dc84ed8aa0d4",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "3f82ea4a-1b92-4724-88e5-5e0a36ae69da",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "a62ce758-2a51-43ba-8523-baedf25cffe1",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "de",
        experience_translation: {
          id: "fd9311b2-7035-41f2-8ef8-d2d13d9badf5",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.768",
          updated_date: "2024-05-24T08:33:22.768",
        },
        customs: {
          custom_highlights: [
            {
              id: "71b7cd85-4ca0-4949-90c8-4180f76aa5a9",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "b257d261-2c6a-499c-a8d3-a03aae2cedf5",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "bf18c320-ec61-464a-b4e3-fe365b92804d",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "56b6d37e-c72c-46b8-960b-e9fcb7bd8174",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "se",
        experience_translation: {
          id: "cf2db153-62ae-448b-87bf-2854de7e92c6",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.8",
          updated_date: "2024-05-24T08:33:22.8",
        },
        customs: {
          custom_highlights: [
            {
              id: "fcfa0843-7cd6-4feb-9663-05e297e140c4",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "2551f953-3e15-4566-a5cc-cd4139415d33",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "6f0aa65a-cc96-4d1c-90de-59497a764634",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "e9586790-343e-4896-9c18-001d5bbaf2cc",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "nl",
        experience_translation: {
          id: "13859e38-67a9-47db-9690-488084e4f36e",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.899",
          updated_date: "2024-05-24T08:33:22.899",
        },
        customs: {
          custom_highlights: [
            {
              id: "e26fdddf-3795-4f3f-bc4a-4cc7c8bc7162",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "bf36c085-e47a-4852-8252-2d720f513da5",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "9ff919a9-8c18-4ea8-ad3d-a22902d5b561",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "cc3bd5dc-5e6f-444a-9f9e-1b596c55f7c0",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "pl",
        experience_translation: {
          id: "c38baed4-32b1-49a7-b322-b6ed527305a0",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.771",
          updated_date: "2024-05-24T08:33:22.771",
        },
        customs: {
          custom_highlights: [
            {
              id: "96a61389-7ae3-4770-a9a8-4e5db339bf46",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "e12e0f95-8ce5-4a44-b0d0-45edb62b4b72",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "ad564826-b830-49f1-a1d0-35f07a454e36",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "6328f73b-a975-4fb6-aac9-89d19c9e302a",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "it",
        experience_translation: {
          id: "0ff6ab39-debc-4cb4-8625-eee357ac49b8",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.765",
          updated_date: "2024-05-24T08:33:22.765",
        },
        customs: {
          custom_highlights: [
            {
              id: "f0a1a51d-1705-4c63-bebc-04a28c41df40",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "91eebe1a-39de-4f54-a3e5-d8befe0eed19",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "e913bb97-b971-40fb-86f2-6456584b73c0",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "953804c0-9a51-4ce5-a555-61526dd4ce96",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "ru",
        experience_translation: {
          id: "4fde4b7f-3e1f-4683-85a1-a66b2a8d79fd",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.774",
          updated_date: "2024-05-24T08:33:22.774",
        },
        customs: {
          custom_highlights: [
            {
              id: "e11a5067-f1e1-4887-bd8c-2510c5cb4945",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "0c77701b-4ac0-4975-a937-f745433e3bbd",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "473093c0-5955-428d-81df-70573aeba46f",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "6db212a6-57f4-454f-bfa1-2b19f5feecbf",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "fi",
        experience_translation: {
          id: "d5f9943a-7316-448d-ad59-465e1e078c55",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.818",
          updated_date: "2024-05-24T08:33:22.818",
        },
        customs: {
          custom_highlights: [
            {
              id: "9e88c682-2b70-4be6-bfa6-7dbde23cf148",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "1490dd54-c08c-40f3-a83f-de36cd427596",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "4b998217-5ac6-48eb-9009-1cb6bbfa5042",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "d8900e43-bee4-40ae-9f2c-dc6de4d26b94",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "dk",
        experience_translation: {
          id: "d71e2626-9303-4f7e-93dc-bcd488e82ab4",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.901",
          updated_date: "2024-05-24T08:33:22.901",
        },
        customs: {
          custom_highlights: [
            {
              id: "846f17f9-5af7-4620-8bd6-32651c5bfc66",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "b439ea4b-8665-4e5a-8e4e-3e6357e58213",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "80b5922c-2015-4506-b456-20ea33958f2c",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "753e0d31-2a68-44e9-811f-d8746aad5f00",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "en",
        experience_translation: {
          id: "6474a7df-e253-486c-af21-f263a34b22be",
          title: "1805906d-b861-4380-bf6e-e06d5c8a6657",
          text1: "<p>Any description</p>",
          text2: "<p>Any Additional description</p>",
          seo_title: "Seo meta title test",
          seo_description: "<p>Any description seo</p>",
          info_voucher: "<p>Any Voucher instructions</p>",
          meeting_point_details: "<p>Any Meeting point details</p>",
          flow_code: "CURATION",
          status_code: "READY",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:10.356",
          updated_date: "2024-06-06T12:45:21.855",
        },
        customs: {
          custom_highlights: [
            {
              id: "5b641de6-4397-43f1-8ddf-5596c290e601",
              code: "local-s1971laoi7",
              name: "Any custom highlights",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "CURATION",
              status_code: "TO_BE_EDIT",
            },
          ],
          custom_included: [
            {
              id: "39dc86e8-18d4-47df-90de-374ea70f987a",
              code: "local-zkzj17qrxzo",
              name: "Any custom included",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "CURATION",
              status_code: "TO_BE_EDIT",
            },
          ],
          custom_non_included: [
            {
              id: "469746a7-adfe-4309-901d-8e478314f677",
              code: "local-xwoyn15szim",
              name: "Any custom non-included",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "CURATION",
              status_code: "TO_BE_EDIT",
            },
          ],
          custom_important_information: [
            {
              id: "b261ef52-286a-491d-884c-fa9fa694e2e2",
              code: "local-c7sjz441zy",
              name: "Any custom important information",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "CURATION",
              status_code: "TO_BE_EDIT",
            },
          ],
        },
      },
      {
        language_code: "no",
        experience_translation: {
          id: "44d4ceae-12d5-429c-b9aa-35e499b2c429",
          flow_code: "MANUAL_TRANSLATION",
          status_code: "TO_BE_EDIT",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:22.91",
          updated_date: "2024-05-24T08:33:22.91",
        },
        customs: {
          custom_highlights: [
            {
              id: "03afd55b-d047-4754-b918-fe9e51f6c1ac",
              code: "local-s1971laoi7",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom highlights",
            },
          ],
          custom_included: [
            {
              id: "208d8e51-74e3-484e-9965-fd0d9443cb57",
              code: "local-zkzj17qrxzo",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom included",
            },
          ],
          custom_non_included: [
            {
              id: "b2e5c693-8e48-4c9a-8da7-73949514f00a",
              code: "local-xwoyn15szim",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom non included",
            },
          ],
          custom_important_information: [
            {
              id: "ce3df14e-4643-45bf-a90a-fb43d5d57341",
              code: "local-c7sjz441zy",
              automatic_translation: false,
              visualization_order: 1,
              flow_code: "MANUAL_TRANSLATION",
              status_code: "TO_BE_EDIT",
              name: "Any custom important information",
            },
          ],
        },
      },
      {
        language_code: "es",
        experience_translation: {
          id: "fb2fb99c-afbb-4da7-846d-8af124a29e6f",
          title: "1805906d-b861-4380-bf6e-e06d5c8a6657",
          text1: "<p>Cualquier descripción</p>",
          text2: "<p>Cualquier descripción adicional</p>",
          seo_title: "Prueba de metatítulos SEO",
          seo_description: "<p>Cualquier descripción SEO</p>",
          info_voucher: "<p>Cualquier instrucción del cupón</p>",
          meeting_point_details: "<p>Cualquier detalle del punto de encuentro.</p>",
          flow_code: "AUTOTRANSLATION",
          status_code: "IN_REVIEW",
          curation_quality: "false",
          creation_date: "2024-05-24T08:33:23.204",
          updated_date: "2024-06-06T12:45:21.761",
        },
        customs: {
          custom_highlights: [
            {
              id: "136c3d50-08e2-4f47-b8d7-b651f4a76dc3",
              code: "local-s1971laoi7",
              name: "Cualquier resaltado personalizado",
              automatic_translation: true,
              visualization_order: 1,
              flow_code: "AUTOTRANSLATION",
              status_code: "IN_REVIEW",
            },
          ],
          custom_included: [
            {
              id: "7ced05cb-1d2d-43b6-9eea-68d47bcdae02",
              code: "local-zkzj17qrxzo",
              name: "Cualquier costumbre incluida",
              automatic_translation: true,
              visualization_order: 1,
              flow_code: "AUTOTRANSLATION",
              status_code: "IN_REVIEW",
            },
          ],
          custom_non_included: [
            {
              id: "b8f68ad6-2604-4e36-9e1c-c9f732c5e914",
              code: "local-xwoyn15szim",
              name: "Cualquier costumbre no incluida",
              automatic_translation: true,
              visualization_order: 1,
              flow_code: "AUTOTRANSLATION",
              status_code: "IN_REVIEW",
            },
          ],
          custom_important_information: [
            {
              id: "a1c21156-9323-4a47-bd60-2bedb0548fd0",
              code: "local-c7sjz441zy",
              name: "Cualquier información importante personalizada",
              automatic_translation: true,
              visualization_order: 1,
              flow_code: "AUTOTRANSLATION",
              status_code: "IN_REVIEW",
            },
          ],
        },
      },
    ],
  },
  experience_functional_information: {
    additional_services: {
      id: "3881bdf0-be34-4d32-9a35-d0b48ccacf68",
      codes: [
        "BRAND_TUI_COLLECTION",
        "OWN_OFFER_TUI_DESIGNED_OPERATED",
        "PROMOTIONAL_SPECIAL",
        "FEATURE_AUDIOGUIDE",
        "DURATION_UP_2",
      ],
      creation_date: "2024-05-24T08:33:10.365",
      updated_date: "2024-06-06T12:45:20.693",
    },
    categories: {
      id: "c4acf0bd-316b-4c2b-94b2-b6447ad6c4c5",
      codes: ["BOAT_TRIPS"],
      creation_date: "2024-05-24T08:33:10.366",
      updated_date: "2024-06-06T12:45:20.778",
    },
    interests: {
      id: "83763e73-6de1-4533-b572-a29301e62249",
      codes: ["WALKING_TOUR"],
      creation_date: "2024-05-24T08:33:10.365",
      updated_date: "2024-06-06T12:45:20.764",
    },
    markets: {
      id: "378c0076-e848-419b-8540-229d79055d50",
      codes: ["bo-2b"],
      creation_date: "2024-05-24T08:32:43.578",
      updated_date: "2024-06-06T12:45:20.78",
    },
    booking_information: {
      id: "4781a6d5-6a49-4a17-9bdc-f24cda48005a",
      experience_id: "6ab12cef-b5bf-4719-ba23-d89edc79af08",
      information: {
        voucher_type: "MOBILE",
        emergency_contact_number: { country_calling_code: "212", number: "0699999999" },
      },
      creation_date: "2024-05-24T08:32:27.312",
      updated_date: "2024-05-24T08:32:47.314",
    },
    booking_questions: [
      {
        id: "9ba27870-608a-4474-88d0-3fdf484ecb40",
        option_id: "722ae6e8-f468-494a-b68d-7fb83bf1ed97",
        questions: [
          { code: "firstname", is_mandatory: true, is_apply_all: false },
          { code: "lastname", is_mandatory: true, is_apply_all: false },
          { code: "departureTime", is_mandatory: true, is_apply_all: false },
          { code: "dateOfBirth", is_mandatory: true, is_apply_all: false },
          { code: "passport", is_mandatory: true, is_apply_all: false },
          { code: "nationality", is_mandatory: true, is_apply_all: false },
          { code: "numberOfParticipants", is_mandatory: true, is_apply_all: false },
        ],
        creation_date: "2024-05-24T08:32:56.638",
        updated_date: "2024-05-24T08:33:06.331",
      },
    ],
    location: {
      id: "2fc6fc41-f3f4-4b39-ae27-80f30661cc56",
      experience_id: "6ab12cef-b5bf-4719-ba23-d89edc79af08",
      latitude: "42.651711",
      longitude: "18.0858801",
      address: {
        direction: "Croatia, Brsečinska ulica, Dubrovnik, Croatia",
        city: "DBV",
        postal_code: "20000",
        country: "Croatia",
      },
      creation_date: "2024-05-24T08:32:39.368",
      updated_date: "2024-05-24T08:32:39.368",
    },
    external_reference_code: "test ref code",
  },
};
