export const highlights = [
  {
    id: "886a5475-07e5-4ac2-ba1f-471f6209311a",
    code: "TRAAVOIDTHETRAFFIC-ZGHW04",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Avoid the traffic of the city with an airport transfer",
    language_code: "en",
  },
  {
    id: "986a5475-07e4-4ac2-ba1f-471f6209311a",
    code: "TRAAVOIDTHETRAFFIC-ZGHW04",
    hierarchical_group_code: "TRANSPORTATION",
    language_code: "it",
  },
  {
    id: "981a5475-07e4-4ac2-ba1f-471f6209311a",
    code: "TRAAVOIDTHETRAFFIC-ZGHW04",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Avoid the traffic of the city with an airport transfer",
    language_code: "es",
  },
  {
    id: "64c82590-9a9a-4836-af43-9ec4ec796150",
    code: "TRARESTYOURLEGSAND-CC9NR3",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Rest your legs and tour the area aboard a comfortable bus",
    language_code: "en",
  },
  {
    id: "62c82590-9a9a-4336-af43-9ec4ec796150",
    code: "TRARESTYOURLEGSAND-CC9NR3",
    hierarchical_group_code: "TRANSPORTATION",
    language_code: "it",
  },
  {
    id: "61gf82590-9a9a-4336-af43-9ec4ec796150",
    code: "TRARESTYOURLEGSAND-CC9NR3",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Rest your legs and tour the area aboard a comfortable bus",
    language_code: "es",
  },
  {
    id: "3c0dc62c-b8a1-4dca-8ffc-97739f4a318f",
    code: "TRAESCAPETHENOISEA-7PGME4",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Escape the noise and traffic of the city for a day",
    language_code: "en",
  },
  {
    id: "3d0dc62c-b8a1-4d23-8ffc-97739f4a318f",
    code: "TRAESCAPETHENOISEA-7PGME4",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Escape the noise and traffic of the city for a day",
    language_code: "it",
  },
  {
    id: "3d0xc621-b8a1-4d23-8ffc-97739f4a318f",
    code: "TRAESCAPETHENOISEA-7PGME4",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Escape the noise and traffic of the city for a day",
    language_code: "es",
  },
  {
    id: "58a82769-d0ae-432f-8506-3ddf27783bb9",
    code: "TRAROUNDTRIPTRANSP-N30BIB",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Roundtrip transportation to your hotel included to make travel easier",
    language_code: "en",
  },
  {
    id: "7c9ee3e4-d786-4b79-b46c-59b295a2d294",
    code: "TRATAKEYOURTRIPOFF-CEZE61",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Take your trip off-road aboard a 4x4 jeep",
    language_code: "en",
  },
  {
    id: "0132cc76-acea-4393-acfe-1e6a0d205603",
    code: "TRAFLEXIBLEDEPARTU-IPA87G",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Flexible departure points - let the tour come to you",
    language_code: "en",
  },
  {
    id: "1b0a1813-0f24-44c0-a8de-3aacc5b3adfc",
    code: "TRAMULTIPLEDEPARTU-E4V6N7",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Multiple departure times throughout the day give you more control over your day of sightseeing",
    language_code: "en",
  },
  {
    id: "7104ad35-bbc0-4f16-bc55-4898cb58419a",
    code: "TRAAVOIDTHETRAFFIC-0VNRN1",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Avoid the traffic - transportation included so you won't be late",
    language_code: "en",
  },
  {
    id: "18cb25a6-cdd7-4722-9d81-35d24da1c362",
    code: "TRAENJOYASPECIALGO-AX3WBA",
    hierarchical_group_code: "TRANSPORTATION",
    name: "Enjoy a special gondola ride through the magic canals of Venice",
    language_code: "en",
  },
];

export const hierarchicalGroups = [
  {
    id: "e488d5b8-af84-4fac-a552-84360a856594",
    language_code: "en",
    code: "TRANSPORTATION",
    name: "TRANSPORTATION",
    parent_code: "HIGHLIGHTS",
  },
];
